Repository Dad-inc-appendchild/Kino, pull requests merged in 2022-03, with the labels that each got.

#42 Create Database with Movie object and endpoints.
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/qaplug_profiles.xml
  .idea/uiDesigner.xml
  backend/pom.xml
  backend/src/main/java/com/dia/backend/data/.keep
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/data/repository/MovieRepository.java
  backend/src/main/java/com/dia/backend/domain/model/.keep
  backend/src/main/java/com/dia/backend/domain/model/Movie.java
  backend/src/main/java/com/dia/backend/view/controller/.keep
  backend/src/main/java/com/dia/backend/view/controller/MovieController.java
  backend/src/main/resources/application.properties
Labels: new-feature

#43 Created Cafe page,
  frontend/cafePage.html
  frontend/css/main.css
  frontend/html/cafePage.html
  frontend/html/navbar.html
  frontend/js/cafe.js
Labels: new-feature

#46 Database + CRUD
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/data/repository/CustomerRepository.java
  backend/src/main/java/com/dia/backend/data/repository/KinoHallRepository.java
  backend/src/main/java/com/dia/backend/data/repository/MovieRepository.java
  backend/src/main/java/com/dia/backend/data/repository/ScreeningRepository.java
  backend/src/main/java/com/dia/backend/data/repository/SeatRepository.java
  backend/src/main/java/com/dia/backend/data/repository/TicketRepository.java
  backend/src/main/java/com/dia/backend/domain/model/Customer.java
  backend/src/main/java/com/dia/backend/domain/model/KinoHall.java
  backend/src/main/java/com/dia/backend/domain/model/Movie.java
  backend/src/main/java/com/dia/backend/domain/model/Screening.java
  backend/src/main/java/com/dia/backend/domain/model/Seat.java
  backend/src/main/java/com/dia/backend/domain/model/Ticket.java
  backend/src/main/java/com/dia/backend/view/controller/CustomerController.java
  backend/src/main/java/com/dia/backend/view/controller/KinoHallController.java
  backend/src/main/java/com/dia/backend/view/controller/MovieController.java
  backend/src/main/java/com/dia/backend/view/controller/ScreeningController.java
  backend/src/main/java/com/dia/backend/view/controller/SeatController.java
  backend/src/main/java/com/dia/backend/view/controller/TicketController.java
  backend/src/test/java/com/dia/backend/data/mapper/DataMapperTest.java
Labels: new-feature

#44 Crud cafe
  .idea/.gitignore
  .idea/Kino.iml
  .idea/misc.xml
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/data/repository/ProductRepository.java
  backend/src/main/java/com/dia/backend/domain/model/Product.java
  backend/src/main/java/com/dia/backend/view/controller/ProductController.java
Labels: new-feature

#48 Cafe fetch
  .idea/compiler.xml
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/view/controller/MovieController.java
  backend/src/main/java/com/dia/backend/view/controller/ProductController.java
  frontend/.htaccess
  frontend/css/main.css
  frontend/html/movieContainer.html
  frontend/js/cafe.js
  frontend/js/main.js
Labels: enhancement, new-feature

#53 JPA joins and bugfix
  .idea/dataSources.xml
  .idea/misc.xml
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/data/repository/ProductRepository.java
  backend/src/main/java/com/dia/backend/domain/model/Customer.java
  backend/src/main/java/com/dia/backend/domain/model/KinoHall.java
  backend/src/main/java/com/dia/backend/domain/model/Product.java
  backend/src/main/java/com/dia/backend/domain/model/Screening.java
  backend/src/main/java/com/dia/backend/domain/model/Seat.java
  backend/src/main/java/com/dia/backend/domain/model/Ticket.java
  backend/src/main/java/com/dia/backend/view/controller/CustomerController.java
  backend/src/main/java/com/dia/backend/view/controller/KinoHallController.java
  backend/src/main/java/com/dia/backend/view/controller/MovieController.java
  backend/src/main/java/com/dia/backend/view/controller/ProductController.java
  backend/src/main/java/com/dia/backend/view/controller/ScreeningController.java
  backend/src/main/java/com/dia/backend/view/controller/SeatController.java
  backend/src/main/java/com/dia/backend/view/controller/TicketController.java
Labels: new-feature

#50 navbar changed padding
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/domain/model/Movie.java
  frontend/cafePage.html
  frontend/css/main.css
  frontend/html/carusel.html
  frontend/html/navbar.html
  frontend/img/SeniorWednesday2.jpg
  frontend/index.html
  frontend/js/main.js
Labels: enhancement

#56 Calender [WIP]
  .gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  backend/pom.xml
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/data/repository/ScreeningRepository.java
  backend/src/main/java/com/dia/backend/domain/model/Screening.java
  backend/src/main/java/com/dia/backend/domain/model/Ticket.java
  backend/src/main/java/com/dia/backend/view/controller/CustomerController.java
  backend/src/main/java/com/dia/backend/view/controller/KinoHallController.java
  backend/src/main/java/com/dia/backend/view/controller/ScreeningController.java
  backend/src/main/java/com/dia/backend/view/controller/SeatController.java
  backend/src/main/java/com/dia/backend/view/controller/TicketController.java
  backend/src/test/java/com/dia/backend/BackendApplicationTests.java
  backend/src/test/java/com/dia/backend/data/mapper/DataMapperTest.java
  frontend/calender.html
  frontend/css/calender.css
  frontend/img/.gitignore
  frontend/js/calender.js
  package-lock.json
  package.json
Labels: new-feature

#57 Booking2
  backend/src/main/java/com/dia/backend/data/repository/CustomerRepository.java
  backend/src/main/java/com/dia/backend/domain/model/CustomerAndTIckersWrappper.java
  backend/src/main/java/com/dia/backend/view/controller/CustomerController.java
  backend/src/main/java/com/dia/backend/view/controller/TicketController.java
  frontend/css/main.css
  frontend/enterprisebookingsite.html
  frontend/js/bookingsite.js
Labels: enhancement, new-feature

#58 Product info
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/domain/model/Movie.java
  frontend/cafePage.html
  frontend/css/main.css
  frontend/html/movieCard.html
  frontend/html/movieContainer.html
  frontend/html/navbar.html
  frontend/img/PavilionLogoCrop.jpg
  frontend/index.html
  frontend/js/cafe.js
  frontend/js/main.js
Labels: enhancement

#59 Create customer now works.
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/domain/model/KinoHall.java
  frontend/js/bookingsite.js
Labels: enhancement

#60 Merge calender and booking
  .idea/sonarlint/issuestore/index.pb
  frontend/calender.html
  frontend/css/calender.css
  frontend/css/main.css
  frontend/js/bookingsite.js
  frontend/js/cafe.js
  frontend/js/calender.js
  frontend/js/loader.js
  frontend/js/main.js
  frontend/js/vendor/modernizr-3.11.2.min.js
Labels: enhancement, new-feature

#64 set phonenumber in modal
  frontend/js/bookingsite.js
Labels: enhancement

#63 Styled cafe page and made navbar links functional
  frontend/cafePage.html
  frontend/css/main.css
  frontend/html/navbar.html
Labels: enhancement

#65 cleanup bookingSite.js
  frontend/calender.html
  frontend/js/bookingsite.js
  frontend/js/calender.js
Labels: enhancement

#66 Data changes
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/domain/model/Movie.java
  frontend/img/moviecovers/flugt.jpg
  frontend/img/moviecovers/france.jpg
  frontend/img/moviecovers/gucci.jpg
  frontend/img/moviecovers/licorice.jpg
Labels: enhancement

#68 Data changes
  backend/src/main/java/com/dia/backend/data/mapper/DataMapper.java
  backend/src/main/java/com/dia/backend/domain/model/KinoHall.java
  frontend/js/calender.js
Labels: enhancement

#69 Show movie info [WIP]
  .idea/sonarlint/issuestore/c/c/cc42b8dd47e508a13acb1089452a268f9d4e8516
  frontend/admin/calender.html
  frontend/css/main.css
  frontend/enterprisebookingsite.html
  frontend/html/movieContainer.html
  frontend/index.html
  frontend/js/main.js
Labels: new-feature

#70 New pictures
  frontend/css/main.css
  frontend/html/carusel.html
  frontend/img/SeniorOnsdagFlugt.svg
  frontend/img/frenchFridayFrance.svg
  frontend/img/seniorWednesdayGucci.svg
  frontend/img/seniorWednesflugt2.svg
Labels: enhancement
